### ISSUE TITLE
Bloated my /var/log/syslog to 27GB by flooding it with an insane number of errors.

### ISSUE THREAD

**Issue by Fowlet** [torculus/DownFall#3] opened 2021-12-17 14:41 UTC
Bloated my /var/log/syslog to 27GB by flooding it with an insane number of errors.

```
Dec 17 12:04:18 desktop gnome-shell[4937]: clutter_actor_get_position: assertion 'CLUTTER_IS_ACTOR (self)' failed
Dec 17 12:04:18 desktop gnome-shell[4937]: Object .FallItem (0x557466f7b480), has been already deallocated — impossible to access it. This might be caused by the object having been destroyed from C code using something such as destroy(), dispose(), or remove() vfuncs.
Dec 17 12:04:18 desktop gnome-shell[4937]: st_label_set_text: assertion 'ST_IS_LABEL (label)' failed
Dec 17 12:04:18 desktop gnome-shell[4937]: Object Clutter.Actor (0x55746095d0d0), has been already deallocated — impossible to access it. This might be caused by the object having been destroyed from C code using something such as destroy(), dispose(), or remove() vfuncs.
Dec 17 12:04:18 desktop gnome-shell[4937]: clutter_actor_add_child: assertion 'CLUTTER_IS_ACTOR (self)' failed
```

**Comment by torculus** [comment] 2021-12-18 03:15
So, this is happening because of the way that the GLib Promise sources are removed. I'm playing around with different fixes, and should hopefully have some commits tomorrow

**Comment by torculus** [comment] 2021-12-19 22:28
Okay, I think this should do the trick. Turns out that a new `GLib.SOURCE_CONTINUE` source was being added on each call of `fi.fall()`

@Fowlet, are you able to checkout this pull request and see if the issue is still happening?

**Comment by torculus** [comment] 2021-12-29 18:01
@Fowlet, can you verify if these issues are still occurring for you? Otherwise I will be closing out the issue

**Comment by Fowlet** [comment] 2021-12-30 17:34
Unfortunately I don't have time to test properly. Any testing on a Debian-like distro should confirm the fix.

**Closed** 2022-01-19 15:09 UTC
